### ISSUE TITLE
Multipage book not showing total number of pages

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#854] opened 2018-02-23 19:57 UTC
### Expected behavior

Based on the UI showing "page X of Y", I would expect to the total number of pages to be shown.  Instead it shows the current page, but the total page count is always a minus sign.

### Actual behavior

Total page count is never shown.

### Steps to reproduce the behavior

Visit https://sul-purl-uat.stanford.edu/bg262qk2288 and look at the bottom of the image viewer

### Browser / Environment

Firefox 58 on Mac
Opera 51 on Mac (Chromium)

**Comment by peetucket** [comment] 2018-02-23 19:58
![screen shot 2018-02-23 at 11 57 56 am](https://user-images.githubusercontent.com/47137/36614214-ce85bcca-1890-11e8-9f50-0b7ef6a4a3bd.png)

**Comment by jkeck** [comment] 2018-02-23 20:30
@peetucket this is part of the content search implementation that is currently being worked on and will not be present in the viewer when we release it (e.g. out of scope for this round of UAT).

This feature is only present when the IIIF manifest defines a search service and none of our production manifests will advertise this search service until we have all these issues resolved.

Closing as a duplicate of sul-dlss/content_search#6 which lead to a change upstream to address it.

**Closed by jkeck** 2018-02-23 20:30 UTC
