### ISSUE TITLE
In IE 11, the scrollTo widget scrolls the whole browser window, not just the immediate scrollable container

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/sul-embed#1035] opened 2019-06-26 17:47 UTC
### Browser / Environment
 MS Edge 42

**Comment by jkeck** [comment] 2019-07-02 18:27
I'm gonna take a quick try at a polyfill.

**Comment by jkeck** [comment] 2019-07-02 21:24
`smoothscroll-polyfill` didn't pan out and didn't change the behavior at all (which may be expected since IE/Edge does have the feature, just implements it in a weird way)

**Comment by mejackreed** [comment] 2020-03-25 23:45
Confirmed that Edge is fixed (80) but issue is present in IE11

**Comment by jcoyne** [comment] 2023-01-05 17:21
IE is EOL, so closing.

**Closed by jcoyne** 2023-01-05 17:21 UTC
