### ISSUE TITLE
Responsive / mobile display - video not centered in viewport

### ISSUE THREAD

**Issue by jvine** [sul-dlss/sul-embed#672] opened 2016-08-25 00:00 UTC
I haven't tested this on my actual phone because I don't know how to VPN. But when I use the Chrome simulator, the player is assuming a much wider space and the video is centered to that, and not to the actual viewport. This happens when the page is reloaded at the narrow size, so it's not just that it's not adjusting as the window is resized. 

![screen shot 2016-08-24 at 4 54 58 pm](https://cloud.githubusercontent.com/assets/6945691/17952053/e637250e-6a1b-11e6-8c35-cb2b21e72058.png)

**Comment by jkeck** [comment] 2016-08-26 16:46
Duplicate of #666

**Closed by jkeck** 2016-08-26 16:46 UTC
Labels: bug, media
