### ISSUE TITLE
User can download all files in an object with a single click

### ISSUE THREAD

**Issue by peetucket** [sul-dlss/sul-embed#1381] opened 2022-11-11 19:53 UTC
**Request**

Add a download button to the bottom of the the embed viewer when:

- content type is file
- rights allow download

The button should provide access to the download all files API: https://api.library.stanford.edu/docs/digital-stacks/api#downloading-all-files-for-a-given-object

Do not show a download icon when rights do not allow download.

**Design**

<img width="380" alt="image" src="https://user-images.githubusercontent.com/8975583/211384855-f139b5a6-3f63-4eaf-924a-b923806c1563.png">

Notes on the design

- Ideally, we would give people an indication of the total download size before they click the button. If that's not possible, just showing a download icon would be acceptable.
- Only show the Stanford 'S' icon if rights are restricted to "Stanford + download"
  - The 'S' icon should be the same icon used when single files are restricted to Stanford ([example](https://purl.stanford.edu/bb057yp4089))
  - If rights are restricted to Stanford, the link should trigger SUnet authentication. That might need an additional flow but if possible it should follow what happens when people click on a Stanford-restricted single file.

If possible, once the button is clicked, show an in-progress indicator and disable the button to prevent multiple clicks in a short period:

<img width="357" alt="image (2)" src="https://user-images.githubusercontent.com/8975583/211386077-0bac0126-b6e1-43d5-9814-8343c8896255.png">

Because the download starts being built in the background before the browser initiates download, there's a concern that users will repeatedly click the button if they don't realize the system is already working on the request.

**Additional considerations**:
- If one file within an object has different access rights (e.g. dark) than others, do not show the "download all" button. Handling cases where file-level rights vary within the same object will require more analysis.
- We are not placing a limit on size of download, either in terms of number of files or size of files. However, it's likely that there is an upper limit to what the system will handle. This may need to be revisited but there are no current limits on the size of individual file downloads and policy concerning maximum download size requires further discussion.
- At the risk of doing a premature optimization we may want to limit how much crawlers will discover and follow links to stacks.stanford.edu to generate the ZIP files since this the rapid, dynamic generation of ZIP files could create some performance issues.

**Additional context**
Objects with many files can take a lot of clicks to download all files, and this will become more of an issue with hierarchical objects with many files.  Users should be able to get all of the files in an object with a single click. This would also benefit the user experience for already existing content that is presented in long file lists in sul-embed.

Some previous work design work for image viewer here: #1187

**Comment by astridu** [comment] 2022-12-15 00:33
Clicking the download icon in the bottom border of the sul-embed module will download all files.
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/42216982/207744693-609cd249-1e60-4a07-a40f-6b1f6668b235.png">

**Comment by andrewjbtw** [comment] 2022-12-16 22:08
If rights are no-download, don't show the download link. This is consistent with no download rules on the embed viewers that already have a download "drawer". If any file is excluded from download, also don't show the link.

There is no set limit to what can be downloaded. But it is known that above a certain point, the download will fail. This is also true of other download contexts (large files).

**Comment by justinlittman** [comment] 2022-12-16 22:08
Additional question: Is this for all content types?

**Comment by andrewjbtw** [comment] 2022-12-16 22:09
Just for file. We're trying not to change anything for all the other content types. Each would need its own design.

**Comment by edsu** [comment] 2023-01-11 20:55
It looks like the latest sul-embed that is checked into git has some existing download functionality for "files" that doesn't seem to match the design I'm seeing above?

<img width="570" alt="Screenshot 2023-01-11 at 3 29 12 PM" src="https://user-images.githubusercontent.com/33829/211915028-264ddb62-87c6-4e78-a619-08813a09234b.png">

When you click on the "4" it brings up an additional pane:

<img width="569" alt="Screenshot 2023-01-11 at 3 48 48 PM" src="https://user-images.githubusercontent.com/33829/211915083-03cea1b0-09fb-4a11-abb2-28165a8b4ac8.png">

Are we removing this functionality? Are we adding *another* download icon?

**Comment by andrewjbtw** [comment] 2023-01-11 21:03
That's not the file content type, which has no download button whatsoever.

**Comment by andrewjbtw** [comment] 2023-01-11 21:23
To be a bit clearer about it, this issue should be confined to the file content type. There are download UIs for each of these content/viewer types that appear through some combination of icon (either in the base or top of the viewer) and drawer or overlay that results from clicking on the icon:

- image
- book
- geo
- document
- 3D
- media

It might turn out to be more feasible to follow one of those patterns (like popping up a drawer with a link), but the difference with respect to the file viewer is the new function being requested is to download all of the files, while the other download UIs provide access to lists of individual files. For the file viewer the list of files is the viewer itself. For the other content types, the list of downloadable files is an overlay on top of the content-specific view.

In testing, we will need to ensure that we do not adversely affect download functions for the other content types.

**Comment by edsu** [comment] 2023-01-11 21:37
Oh, thanks @andrewjbtw! I was confused by the Useful Druids list that had tn629pk3948 as "Files":

<img width="1699" alt="Screenshot 2023-01-11 at 4 21 25 PM" src="https://user-images.githubusercontent.com/33829/211923053-30b55567-b59f-4b36-b502-ef203ad4a3fb.png">

**Comment by justinlittman** [comment] 2023-01-12 16:55
For consideration, how will download interact with the search? Will this be confusing for the user?
![image](https://user-images.githubusercontent.com/588335/212130400-106f461d-78ad-4a85-a7c0-ac6c79b81b64.png)

**Comment by andrewjbtw** [comment] 2023-01-13 17:48
It won't interact with search at this point. Downloading all will always download all. I think there are use cases for selecting files for download but that would likely need a new UI design.

**Comment by edsu** [comment] 2023-01-13 22:05
#1420 includes a first pass at the **Download All** functionality for all File objects where the files are all downloadable. 

Some caveats:

1. There is no "download in progress" button. In theory it should be possible to add this, but I'm not sure it will be easy to flip it back to "download" once the download has finished.
2. It depends on logic in Stacks to trigger the SUnet authentication for Stanford Only objects. I noticed that if you are off campus and try to download an object whose files are only available on campus that Stacks returns a 404 error. I believe that if some files in the object are available off campus then the ZIP file will only include those files. I don't think it's feasible to move this logic outside of Stacks, but perhaps we could make some changes to Stacks to match the expected behavior?

**Comment by edsu** [comment] 2023-01-17 16:50
I'm wondering if JavaScript might really be needed to prevent crawlers from coming in and crawling the ZIP download links?

**Comment by edsu** [comment] 2023-01-17 19:08
@jcoyne that's a good point, and preferable to adding more JavaScript to the mix at this stage.

We might want to consider adding `/object/` to https://stacks.stanford.edu/robots.txt too?

**Comment by edsu** [comment] 2023-01-17 19:20
I added some notes about the need to nofollow to the initial description.

**Comment by edsu** [comment] 2023-01-18 16:06
Hi @ggeisler -- @mjgiarlo let me know that it would be helpful to see a short screencast of what these changes look like for your feedback. 

https://user-images.githubusercontent.com/33829/213225645-3edfca06-abc6-43c4-beac-5ff42813f93e.mp4

Let me know if you need any more information to help with this, and thanks for your assistance on this.

**Comment by jcoyne** [comment] 2023-01-18 16:34
@edsu what does it display if the object only has one file?  What if it's a metadata only object (no files)?

Can the endpoint handle a very large object that might time out when downloading?  If someone launched say 20 simultaneous downloads on a slow connection, will that DOS the server?

**Comment by edsu** [comment] 2023-01-18 16:37
I think it could potentially DOS the server yes. The original design calls for disabling the button once clicked, but I that will involve adding to the jQuery code. It sounds like you are in favor? From the initial description I believe POs are aware of existing limitations on download size.

**Comment by jcoyne** [comment] 2023-01-18 16:43
@edsu I think some of the questions are for @ggeisler and it may help him if you make screenshots for each of those test scenarios.

**Comment by andrewjbtw** [comment] 2023-01-18 16:59
> what does it display if the object only has one file? 

It will look the same in the current design.

>What if it's a metadata only object (no files)? 

If no files are shelved, there's no embed viewer at all.

> What does the stanford only version of the download look like for a not-signed in user?

It's in the design with the red S. This is consistent with the red S showing next to Stanford only files whether or not the user is signed in.

> Can the endpoint handle a very large object that might time out when downloading? 

Probably not. This download all feature was implemented in Stacks 2-3 years ago and I don't know of any load testing that was done. I have downloaded 30 GB.

> If someone launched say 20 simultaneous downloads on a slow connection, will that DOS the stacks server?

I don't know. How do we protect against that in single-file downloads currently?

> Do we have the correct UI if one file is marked "no-download"? Will the user be confused if the button just doesn't display?

Not showing the download button is consistent with the UI for the media viewer. That viewer shows a download icon (which opens a drawer with a list of files) if downloading is allowed and does not show the download icon if the downloading is not allowed. I believe the download icon did show at one point even on no-download objects but users reported finding it confusing to be presented with a download link that then denied them permission to download, so the icon was removed.

The book and image viewers show a download icon all the time because people are able to download thumbnail images even when rights do not allow download of full images. This has been a source of user confusion as well.

**Comment by jcoyne** [comment] 2023-01-18 17:22
@andrewjbtw the first four questions were meant to be "Provide screenshots for these situations"

Regarding timeouts, should we limit the size of downloads offered?  Single file downloads are often a great deal smaller than a zip of everything, so I'm wondering do we need to increase our capacity if we expose this new UI element?

Showing or not showing a button is one option we can take. We also have the option to tell users "Download not available because file foo/bar/baz.jpg is no-download" or something like that.

**Comment by ggeisler** [comment] 2023-01-18 18:14
@edsu Thanks for the video. Overall, this looks good to me, and seems to match the original design. A couple of thoughts:

- In the single file case, are you using `pluralize` or something similar to adjust the button label text? I think it will read a bit oddly if you follow the current pattern: `Download all 1 files (44 kB)`. Even singularizing "files" will still read: `Download all 1 file (44 kB)`. So if you can change the label more substantially in the single file case, such as: `Download (44 kB)` that seems ideal.

- Astrid might have tried this in the mockup phase and discarded the idea because it doesn't work too well, but if not, I'm curious if we really need the white border around the download button? Because there's no similar border around the other two icons, it makes the download button stand out stronger than them (as if it's more important). The border does provide a clear container for all of the download button elements (icon, text pieces) so I see that value, but also am wondering if -- as long as the text is tight against the icon, which it currently seems to be -- omitting the border would reduce the prominence of the download button while still clearly conveying its purpose. Something easy to try and discard if it doesn't seem to work.

- Very minor, but I'm curious to see the "Download in progress" state. In the design provided the Stanford S stays in place when the button label changes to the "Download in progress" message (maybe not intended but just a mockup artifact); ideally, I think we might want to remove it once the download starts, just because it feels a bit odd sitting out there on its own, and it doesn't really have much value to the user once the download is underway. (This might be more important if we decided to forgo the button border, as described above.)

There were a lot of other comments in this ticket so if there is anything else in particular you'd like my feedback on that I missed, let me know.

**Comment by astridu** [comment] 2023-01-19 00:34
@jcoyne @ggeisler @andrewjbtw 
I spoke with Andrew about most of the items above. Here's what we decided:
1. Do not display download icon in the lower bar if there is only 1 file to download.
<img width="866" alt="image" src="https://user-images.githubusercontent.com/42216982/213327271-7c24efa0-b10f-4726-9117-c953258a700e.png">
2. Remove the 'all' and outline from the download all link in the lower bar.
<img width="362" alt="image" src="https://user-images.githubusercontent.com/42216982/213327435-8ae5b9db-fe16-474b-b400-1115f1e78f40.png">
3. Once user clicks the download all link in the lower bar, display "Initiating download..." in place of the download text until the file window comes up allowing user to download the files. 
<img width="362" alt="image" src="https://user-images.githubusercontent.com/42216982/213327626-5af33a4f-0407-4be5-acbc-46649534a933.png">
4. If files exceed 10GB, display this message instead of download all icon and link.
<img width="590" alt="image" src="https://user-images.githubusercontent.com/42216982/213327990-5295fb91-cda1-4dd7-8e99-10c6b11dd590.png">

**Comment by ggeisler** [comment] 2023-01-19 00:56
@astridu Those sound good to me. Though for item 2, I thought about suggesting removing the "all" when commenting on the wording of the message but wasn't sure how that might interact with the search filter behavior. For example, if the user filters some files and the "N items" value in the top bar is then fewer than the number in the full set of items, is it confusing that the number in the "Download N files" bottom bar label doesn't match? I thought that maybe the "all" would help clarify that, a tiny bit. But that's probably a special and minor case. And I really like the label better without the "all" so not opposed to doing it.

**Comment by jcoyne** [comment] 2023-01-19 00:58
@astridu what should be the aria-label of the stanford "S"?

**Comment by andrewjbtw** [comment] 2023-01-19 00:59
Some background on the "contact us" message, which is new: this came out of discussion over whether attempting to download a large object could disrupt the system. There does seem to be a real risk of overloading Stacks if a download has too many files or too many bytes. We have a number of objects above the 100 GB range, including some datasets that people have attempted to download before (as individual files).

It's open to discussion where exactly we should set the limit. I'm not sure how to determine that. But in testing on stage, I'm pretty sure that my test object with 10,000 files is causing disruptions to stacks-stage. Each time I try to download it, nagios starts showing "critical" messages.

**Comment by astridu** [comment] 2023-01-19 17:33
> @astridu what should be the aria-label of the stanford "S"?

Restricted to Stanford

**Comment by edsu** [comment] 2023-01-19 23:19
For the  "Initiating download..." functionality discussed above, sometimes seemingly simple things turn out to be hard.

Without getting into some [trickery with cookies](https://stackoverflow.com/questions/1106377/detect-when-a-browser-receives-a-file-download) it appears that the only way to get notified when the download starts (in order to enable the button again) is to use the [Download API](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/downloads/download) which needs run as an extension, and (unless I'm missing something) isn't really feasible for the multiple places where sul-embed is used.

I think a more reliable (albeit complicated) approach would be for the Stacks API to allow the client to request that the ZIP be created, and then to poll and wait for it to be ready. Here's a draft proposal for what that might look like:

```mermaid
sequenceDiagram
Note over Client: User clicks Download and the button text changes to "initiating download"
Client->>Server: POST  /object/sg052hd9120 
Server-->>Client: HTTP 201 Location: /jobs/12345
Note over Client: Client begins polling to see if ZIP is ready
Client->>Server: GET /jobs/12345
Server-->>Client: HTTP 200 { status: queued }
Client->>Server: GET /jobs/12345
Server-->>Client: HTTP 200 { status: running }
Client->>Server: GET /jobs/12345
Note over Server: Server notifies client that the ZIP is ready!
Server-->>Client: HTTP 200 { status: done, url: /download/12345.zip }
Note over Client: Download button text is changed back to "download" and the client initiates download
Client->>Server: GET /download/12345.zip
Server-->>Client: HTTP 200 Content-Type: application/zip
```

This would allow the client to notice when the ZIP download is ready, and update the button text before the download starts. It would also allow Stacks to queue up these zip packaging jobs so that they are handled in a scalable way instead of potentially flooding the server with requests, some of which could be for the same ZIP file (like when a class is downloading the item, or the item is shared in social media and it goes viral).

---

All that being said, for now we can disable the button when a user clicks on it and see if we can get by with that for now. It will at least avoid a situation where a user repeatedly clicks the button when they don't see a change, which will trigger multiple requests (and server side zip processes) for the same ZIP file. We just won't be able to renable the button after the download starts.

**Comment by justinlittman** [comment] 2023-01-20 12:16
ActionCable / Websockets is another alternative.

**Comment by edsu** [comment] 2023-01-20 13:16
@justinlittman I would definitely be interested to learn how ActionCable / Websockets could help here.

**Comment by jcoyne** [comment] 2023-01-20 16:11
@edsu why do we need to precreate a zip? Creating it as a stream seems superioras it's zipping as you download it which means we don't have to manage these files between multiple servers and clean them up afterwards.

**Comment by edsu** [comment] 2023-01-20 20:55
@jcoyne that's neat that zipline streams the Zip back as it's being created -- I actually missed that detail when looking at Stacks.

I believe that @andrewjbtw has found SDR objects that fail to respond to the request for the Zip. I was thinking that if they were generated on demand via an API like the one above then it would be more reliable, and could also allow for ZIPs to be placed on a CDN potentially in the future, if that was important for Data Commons work.

But I admit, it might be over-engineered, and could use to be simplified.

**Comment by andrewjbtw** [comment] 2023-01-23 17:57
@edsu Thanks for the updates. In my second round of testing, things look good overall. I need to think about/get more feedback on the text of the messages, but the logic looks right on when there's a download button vs a contact us message. I'm also still looking at whether to adjust the threshhold for when to show contact us.

The one issue I'm seeing is with Stanford authentication. The browser must be treating the link to Stanford's login site as embedded in the viewer because I'm getting error/security messages within the viewer when I click while non-authenticated.

Firefox:

<img width="1213" alt="Screen Shot 2023-01-23 at 9 18 11 AM" src="https://user-images.githubusercontent.com/8975583/214113661-44332c35-828d-4410-a766-df1e1607cff3.png">

Chrome (screen recording):


https://user-images.githubusercontent.com/8975583/214113706-8eef4410-8482-4365-94dc-4b2b5117252e.mov

When I'm already authenticated, the download proceeds as expected. This is the purl I'm using for Stanford auth:
https://sul-purl-stage.stanford.edu/hf050sp3296

**Comment by edsu** [comment] 2023-01-24 15:00
It does seem like something in the interaction between Chrome (at least in Incognito mode) & SSO doesn't like JavaScript adding an `<a>` element and clicking on it. Adding the `<a>` to the page directly does seem to work, so I'm going to adjust things to load that way.

**Comment by andrewjbtw** [comment] 2023-01-24 17:45
From my latest testing + some additional feedback from PSM:

- I've been able to download all from Firefox, Safari, and Chrome on MacOS, plus Firefox and Safari on iOS
- The conditional appearance of the link vs the message seems to be working correctly, but I think we also need it to count files (more on scale testing below)
- The conditional appears on 2 or more files (but not 1) also is working as expected

I did find a few issues, plus one change requested based on feedback:

**Download "all" message**

PSM-ers felt that the "all" in "Download all N files" would help clarify that the download will get all files in the context when the viewer is filtered to a search that shows a smaller number of files in the box. I think there's less concern about "all" being an issue in other contexts because the message simply doesn't display when there's only one file.

**Location-restricted content shows zero files**

When content is restricted to a location, the message still appears but offers a download of zero files.

<img width="454" alt="Screen Shot 2023-01-24 at 9 24 58 AM" src="https://user-images.githubusercontent.com/8975583/214364453-e96b8129-0518-4599-967f-e508caceaed2.png">

This rights setting means that files are available only on authorized workstations within a library building (specific to each location). I think we should not show the download all under this rights setting.

**Large downloads**

I did more testing of scale and I'm confident that the combination of large numbers of files and file size is more of an issue than downloading large numbers of bytes. I repeatedly tried to download all the files in this prod object (using the API call directly) and it failed. There are only about 3.6 GB of data on Stacks for that object, but over 4000 files.

It seems to me that a threshold of 3000 files or 10 GB would be a good place to start. I've consistently been able to download in the 3000 file range, both on stage and prod.

**View on narrow browser widths/phone**

The whole "Download + link" message shows at narrow screen widths, including on my work phone (an iPhone 11?). On the phone, I don't see a message at all:

![Screenshot 2023-01-24 at 9 30 43 AM](https://user-images.githubusercontent.com/8975583/214367294-bb6d4efd-879e-435f-a2b5-80e6f6b7dc31.jpeg)

In the browser, the message is cut off:

<img width="454" alt="Screen Shot 2023-01-24 at 9 34 43 AM" src="https://user-images.githubusercontent.com/8975583/214367411-7f57a40c-544e-4225-9cbd-5a101643d437.png">

@astridu what would you advise here for narrow screen widths?

**Comment by edsu** [comment] 2023-01-24 22:17
Since the condition for displaying the email instead of the link is now > 10GB or > 3000 files could we perhaps just display:

To download please email?

Where "email" is a hyperlink `mailto:sdr-contact@lists.stanford.edu link?` that should open an email program?

**Comment by astridu** [comment] 2023-01-24 22:27
I'm ok w/this if @amyehodge is ok.

**Comment by andrewjbtw** [comment] 2023-01-24 22:41
The email as hyperlink saves us a lot of space. I'm not sure about calling it "download" when it's the alternative to downloading.

**Comment by astridu** [comment] 2023-01-24 23:59
To us, it is the alternative to downloading, but to the user, that's the action they want to do.

**Comment by andrewjbtw** [comment] 2023-01-25 01:01
Good point. What about:

>Need help downloading? Contact us.

But that might still be too long.

**Comment by andrewjbtw** [comment] 2023-01-25 01:03
Or

>Trouble downloading? Contact us.

**Comment by astridu** [comment] 2023-01-25 01:21
Contact us to download files.

**Comment by edsu** [comment] 2023-01-26 16:54
Just noting here something that @andrewjbtw turned up in testing. It looks like on mobile the Download All icon and message disappear because they get pushed to the next line, and the bottom toolbar has a fixed height.

One way of fixing this might be only to display the download icon on mobile.

**Comment by andrewjbtw** [comment] 2023-01-26 23:23
@edsu Sorry for the delay. We are ready to go forward with this as it currently stand.s

**Closed** 2023-01-27 15:57 UTC
