### ISSUE TITLE
Multi-item object film-strip conceals body of content

### ISSUE THREAD

**Issue by snydman** [sul-dlss/sul-embed#630] opened 2016-08-04 22:44 UTC
@jvine @ggeisler - I notice in the wonderful media sprint demo the capability of displaying multiple first-class items in the embed view for an object (eg, audio file plus thumb).  The UX convention used to reveal the multi-items is similar to the convention used for a multi-image object filmstrip (such as a book or manuscript). 

In both cases this filmstrip, when revealed conceals part of the body of the object (the video, the image, etc.)  The image viewer is being reworked so that the film strip is below the image always and does not conceal the main image in the viewport.  An alternative approach would be to move the film strip to the left of the embed widget and position it vertically. 

Is adjusting the layout of the embed widget so that the filmstrip does not block the content something we can consider?

**Comment by snydman** [comment] 2016-08-04 22:57
see: 
![image](https://cloud.githubusercontent.com/assets/3279382/17421115/2348e600-5a5c-11e6-84da-4f5042ecd573.png)

**Comment by aeschylus** [comment] 2016-08-05 00:08
Previously when we've talked about this, the interim solution was to have the filmstrip closed by default. I'll point to where that can be done, but a deeper fix for this would be something similar to Mirador's sidepanel/new bottom panel. The content area should be in the negative space left by the bottom panel when it's open. When the bottom panel closes, the content area should expand as it shrinks, sort of "see-sawing" it into position so that whatever is currently framed in the viewport is simply framed in a smaller/larger space that it was before.

To change the default, have a look at: 
https://github.com/sul-dlss/sul-embed/blob/master/app/assets/javascripts/modules/image_x_viewer.js#L43-L50

That is where the toggle is performed. The toggle reads from the layout state store. To understand this language see: https://scotch.io/tutorials/getting-to-know-flux-the-react-js-architecture

To change the default see the layout store itself: 
https://github.com/sul-dlss/sul-embed/blob/master/app/assets/javascripts/modules/layout_store.js#L19-L30

At least for the image viewer, the long-term content-area will be handled through the manifestLayouts API and reshaping will likely go here: https://github.com/sul-dlss/sul-embed/blob/master/app/assets/javascripts/modules/image_x_viewer.js#L40-L42

This model of having a central description of the layout's state represented in a UI-independent way makes having multiple consumers (in this case both the bottom panel module and the main content area components consume this piece of descriptive UI data) a 0-configuration change. If a minimap were added, for instance, we would not have to make any change to how the data is represented or what other components do in response to this data changing. See: Nicholas Hery's post on [Describing UI State with Data](http://nicolashery.com/describing-ui-state-with-data/), Facebook's [Flux Architecture presentation](https://facebook.github.io/flux/docs/overview.html) (or this more [digestible description](https://scotch.io/tutorials/getting-to-know-flux-the-react-js-architecture)) and The introduction to cycleJS ([text](http://cycle.js.org/)), ([video](https://egghead.io/courses/cycle-js-fundamentals)) for why these kinds of problems recur and how to address them through their root cause.

**Comment by peetucket** [comment] 2016-09-06 21:07
example object: https://purl.stanford.edu/fw090jw3474

**Comment by ndushay** [comment] 2016-09-08 20:42
it is my understanding that we will fix this by having the filmstrip for the image viewer be closed by default, as it already is for the media viewer. 

The more complex approach mentioned by @aeschylus is out of scope for either viewer now sporting a thumb index filmstrip.

**Comment by ndushay** [comment] 2016-09-08 22:52
If a further fix is desired, I will leave it to @snydman or @aeschylus  to create a new ticket for that.  I am closing this one.

**Closed** 2016-09-08 22:53 UTC
Labels: bug, in progress, media
