### ISSUE TITLE
Captions jump up and down when watching in fullscreen on Safari Version 16.6 (18615.3.12.11.2)

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#1639] opened 2023-10-31 19:02 UTC
### Expected behavior
The line of captions that display should be consistent while the media is streaming, and the captions should not change locations. 

### Actual behavior

https://github.com/sul-dlss/sul-embed/assets/9371978/28406e68-84dc-4507-9728-c23f92e10525

### Steps to reproduce the behavior
Play https://sul-purl-stage.stanford.edu/rz125dy0428 in Safari and press the button for fullscreen, select english captions.

### Browser / Environment
Safari Version 16.6 (18615.3.12.11.2)

**Comment by jcoyne** [comment] 2023-11-01 15:26
This movement was caused by your mouse hovering over the video element, causing the scrollbar to display and pushing the captions up higher.  This is the behavior visible in all browsers as far as I can tell.

**Comment by mjgiarlo** [comment] 2023-11-01 16:30
We think this happens across browsers.

**Comment by mjgiarlo** [comment] 2023-11-01 16:31
This one does not seem actionable unless we re-position the scrub bar, so we're inclined to close this.

**Closed by mjgiarlo** 2023-11-01 16:31 UTC
