### ISSUE TITLE
“Stanford-affiliated? Login to play” message still displays after login

### ISSUE THREAD

**Issue by caaster** [sul-dlss/sul-embed#1113] opened 2020-02-25 23:50 UTC
### Expected behavior
For this exhibit item: https://exhibits.stanford.edu/1947-partition/catalog/gq296zn8357 - I expect that after I login as a Stanford affiliate (or if I am already logged in as a Stanford affiliate) that I no longer see the message displayed in the viewer that reads: “Stanford-affiliated? Login to play”

### Actual behavior
For this exhibit item: https://exhibits.stanford.edu/1947-partition/catalog/gq296zn8357 — even when I am logged in, the red “Stanford-affiliated? Login to play” message — still displays. Just reported by a curator and verified by me.

### Steps to reproduce the behavior
Go to: https://exhibits.stanford.edu/1947-partition/catalog/gq296zn8357
Login as a Stanford affiliate
See that the message asking you to login still displays

### Browser / Environment
Google Chrome Version 80.0.3987.122 (Official Build) (64-bit)
Mac OS Mojave Version 10.14.6

**Comment by mejackreed** [comment] 2020-02-25 23:51
Duplicate of https://github.com/sul-dlss/sul-embed/issues/862 closing now.

**Closed by mejackreed** 2020-02-25 23:51 UTC
Labels: bug
