### ISSUE TITLE
Redesign the info, embed, associated files, and download drawers in the media player

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#1535] opened 2023-10-16 20:55 UTC
### Actual behavior
In the current media player, when a user clicks on the "i" icon for information, the icon for an embed code, or the download icon (if present), a drawer expands into the media player and obscures the media. A user can also click the three dots (meatballs) to expand an additional drawer to view the associated files within a media object. Drawers expand over one another, and obscure the drawer for viewing the associated files within a media object. The layout of the icons within the player and functionality of these drawers is confusing for users and at odds with a contemporary media streaming user experience.

### Expected behavior
Drawers should not come from the bottom of the media player. Drawers should not cover one another when opened. Ideally, the icons and functionality of the media player should have more cohesion with the image/book viewer (mirador) with regards to placement and behavior of icons. 

### Steps to reproduce the behavior
Open https://purl.stanford.edu/bb169jj6514 

### Browser / Environment
Chrome/iOS

**Comment by jcoyne** [comment] 2023-10-16 22:42
I believe this is a duplicate of #1526

**Comment by dinahhandel** [comment] 2023-10-17 18:14
@jcoyne in my opinion, #1526 is too narrow and the purpose of this ticket is to provide design direction for @alundgard.

**Comment by alundgard** [comment] 2023-10-25 22:22
- See the Header and Left/Right Companion Windows (aka "panels" or "drawers") in the [Figma Design](https://www.figma.com/file/ADNitlk4aWHDiPDWD1dHdF/Media-Work-Cycle---Media-Player?type=design&node-id=0-1&mode=design). [To launch the interactive prototype in Figma, click the "Present" play arrow in the top-right corner.]
- Also, see the Left Companion Window in [Mirador](https://purl.stanford.edu/cs471vd0839).
- Contact me for additional context.

**Comment by jcoyne** [comment] 2023-10-30 15:37
This is previewable at https://embed-stage.stanford.edu/iframe?new_component=true&url=https://sul-purl-stage.stanford.edu/cm856pm4228&_v=1698170929

**Comment by alundgard** [comment] 2023-11-03 18:38
Reopening this issue to reflect design changes to the right companion window. The design will now emulate Mirador even more closely.

- Instead of appearing in the right companion window, the Media Content section will appear as a tab in the left companion window vertical tab group.
- The Share and Download sections are now modals, selected from a dropdown in the top-right navigation bar.

See the "Single Companion Window Desktop" prototype in the [Figma Design](https://www.figma.com/file/ADNitlk4aWHDiPDWD1dHdF/Media-Work-Cycle---Media-Player?type=design&node-id=0-1&mode=design). [Click the "Present" play arrow in the top-right corner and select this prototype.]

See any Mirador example, such as: [https://purl.stanford.edu/bb627py6670](https://purl.stanford.edu/bb627py6670).

**Comment by alundgard** [comment] 2023-11-03 19:13
Re-closing this issue, and creating a new one: #1673

**Closed by alundgard** 2023-11-03 19:13 UTC
Labels: design
