### ISSUE TITLE
correct media filmstrip movie icon placement

### ISSUE THREAD

**Issue by ndushay** [sul-dlss/sul-embed#586] opened 2016-06-08 23:06 UTC
seems to be falling off bottom of box for movie (in purl context, but not sul-embed local bare iframe?).

![filmstrip alignment](https://cloud.githubusercontent.com/assets/96775/15914091/f165d03a-2d92-11e6-8845-f6e8c7bb4aae.png)

**Comment by jkeck** [comment] 2016-06-09 22:27
This appears to be caused by PURLs css clashing with the SUL-Embed css.  I have not been able to track down exactly what css is clashing.

**Comment by ndushay** [comment] 2016-06-10 20:37
#592  partially fixed it:

```
This makes it less embarrassingly wrong, but there is still some sort of css clash going on around the icons and border that should be investigated.
```

## xv428cw8400 (after)
<img width="491" alt="xv428cw8400-after" src="https://cloud.githubusercontent.com/assets/96776/15972785/2eb917cc-2ef5-11e6-82a0-07e821efc3f2.png">

**Comment by jkeck** [comment] 2016-07-25 21:15
We should evaluate if this is still an issue once we move to an iframe.  This is mostly coming form a collision with the embedding site's CSS, which I don't believe will happen once in the context of an iframe.

**Comment by jkeck** [comment] 2016-08-15 22:47
iframe code has been merged, if anything comes up in the future we should ticket it separately.

**Closed by jkeck** 2016-08-15 22:47 UTC
Labels: design, media, on deck
