### ISSUE TITLE
Redesign the way that access restrictions look for location-based and stanford only items in the media player

### ISSUE THREAD

**Issue by dinahhandel** [sul-dlss/sul-embed#1536] opened 2023-10-16 21:01 UTC
### Requirement
As a SearchWorks user on the record for an SDR media item with streaming access restricted to a particular location, I need clear, easy to find information about where I can physically go to play the media. As in this example, the message refers me to “access conditions” for more information, but getting that information requires clicking inside the viewer controls and reading through a lot of metadata or scrolling all the way to the bottom of the MODS metadata where the access info is completely buried.

### Expected behavior
A more stylized message to users when they are not authenticated or in the right location to view stanford only or location-based access that is in line with the overall media player redesign is desirable.

### Actual behavior
Currently access restrictions for stanford and location-based materials display in the media player window with little styling or aesthetic. The text is black and the background is white, making it look almost like a piece of paper displaying the restriction.

Reading room: 
![Screenshot 2023-10-16 at 4 57 41 PM](https://github.com/sul-dlss/sul-embed/assets/9371978/11f7806f-16fd-40c8-b598-0f46905f697b)

Stanford only
![Screenshot 2023-10-16 at 4 58 48 PM](https://github.com/sul-dlss/sul-embed/assets/9371978/b118cac3-6449-477a-86da-7904a9505f5b)

Note that citation only media display is a separate issue.

### Steps to reproduce the behavior
Open https://purl.stanford.edu/bb453jf8328

**Comment by jcoyne** [comment] 2023-10-16 22:40
I believe this is a duplicate of #1531

**Comment by dinahhandel** [comment] 2023-10-17 18:12
@jcoyne it is related but the design should be revised for all access restrictions. 

See also: https://docs.google.com/document/d/1RgP8Js_x4_jGl1S9QkxvD6G2F_C-rG-TgOZPlNtune8/edit?usp=sharing

**Comment by dinahhandel** [comment] 2023-10-25 16:46
@andrewjbtw and I also need to provide updated language to display, but is that a separate ticket @jcoyne @alundgard ? I am differentiating between the design and placement of the message and the content of the message.

**Comment by jcoyne** [comment] 2023-10-25 17:37
@dinahhandel I think the length of the message you use could definitely influence the design. I think those things need to go together.

**Comment by alundgard** [comment] 2023-10-25 18:57
Regarding design and placement, my initial thought is that these messages could appear in a banner similar to the cardinal-red Access Restriction banner in [this Mirador example](https://purl.stanford.edu/bb627py6670). Clicking "Continue" expands the banner to reveal the Access Conditions. Happy to find a time to discuss this design direction.

**Comment by dinahhandel** [comment] 2023-10-25 19:55
@alundgard can we discuss at our next UX/PO meeting? @andrewjbtw and I can come with language suggestions. This is something that we will need to run by stakeholders for approval.

**Comment by alundgard** [comment] 2023-10-25 21:27
Sgtm! @dinahhandel

**Comment by alundgard** [comment] 2023-10-30 21:00
- See the Access Banner Prototype in the [Figma Design](https://www.figma.com/file/ADNitlk4aWHDiPDWD1dHdF/Media-Work-Cycle---Media-Player?type=design&node-id=0-1&mode=design). [To launch the interactive prototype in Figma, click the "Present" play arrow in the top-right corner. From this tab, click Access Banner Prototype under the "Flows" panel.]
- Also, see the Access Banner restriction messages (subject to change, pending stakeholder feedback).
![Image](https://github.com/sul-dlss/sul-embed/assets/2343316/8ec0eec3-8c3f-482a-86b6-26ed1ad123dd)
- Contact me for additional context and/or design revisions due to technical feasibility.

**Closed** 2023-11-03 20:15 UTC
Labels: design
