### ISSUE TITLE
Captions are off-center if they appear on the screen prior to playback

### ISSUE THREAD

**Issue by andrewjbtw** [sul-dlss/sul-embed#2258] opened 2024-11-19 17:58 UTC
### Expected behavior

Captions should use the same text alignment whenever they are displayed on screen.

### Actual behavior

If a video starts with the captions already displayed, the text is pushed to the right. It then aligns properly after the next set of text gets loaded.

https://github.com/user-attachments/assets/c937a1ba-2c93-4ada-9987-52bfc94199ce

### Steps to reproduce the behavior

Go to [this item](https://sul-purl-stage.stanford.edu/vh170nm3897) and then play it back.

### Browser / Environment
Chrome, Firefox, Edge on Mac. Safari is, as usual, weird in its own way.

**Comment by jmartin-sul** [comment] 2024-11-19 20:25
If you wait for the video to fully load, then this happens.  If you start playing the video immediately, it might not happen.

**Comment by jcoyne** [comment] 2024-11-19 20:25
<img width="1048" alt="Screenshot 2024-11-19 at 2 24 42 PM" src="https://github.com/user-attachments/assets/4c289e73-dacb-4aaf-8155-08319e64e045">

It seems to be due to the "inset-inline" css rule on this element.

**Comment by dnoneill** [comment] 2024-11-19 21:57
It is also because the text track is on the screen when the sidebar opens.

**Comment by dnoneill** [comment] 2024-11-19 22:12
Also it seems the sidebar is doing weird things to the video tag on smaller screens

**Comment by dnoneill** [comment] 2024-11-20 23:37
Not the sidebar. Issue is caused by https://github.com/dnoneill/video.js/blob/main/src/js/tracks/text-track-display.js#L128-L132 being triggered after https://github.com/dnoneill/video.js/blob/main/src/js/tracks/text-track-display.js#L127

**Comment by dnoneill** [comment] 2024-11-21 16:17
When I went to create a PR to fix this in videojs's main branch, the texttrackchange was being triggered after loadedmetadata thereby fixing the issue. I have added a patch to sul-embed. My guess, unless something changes with videojs that the newest release should 🤞 fix the issue.

**Comment by jcoyne** [comment] 2024-11-21 18:33
@dnoneill it looks like we are not using an up to date version of videojs: https://github.com/sul-dlss/sul-embed/blob/f4f90b07953e0d8981dd5d9221dea81ceb6b00b2/config/importmap.rb#L16C54-L16C61. Have you tried updating it?

**Comment by dnoneill** [comment] 2024-11-21 18:50
Yes and deployed to stage, didn't fix the problem.

**Comment by jcoyne** [comment] 2024-11-22 17:38
@dnoneill Can you make a PR for that branch? I think we'd want that change merged in.

**Closed** 2024-12-17 22:09 UTC
Labels: bug
