### ISSUE TITLE
PDF/3D viewers: info, share, download, full screen buttons not responding

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/sul-embed#1154] opened 2020-05-19 17:31 UTC
### Expected behavior

Info, share, download, full screen buttons for PDF/3D objects should show their appropriate panels/take the appropriate action. AV objects are not impacted

### Actual behavior

Clicking buttons does nothing; no errors reported in JS console

### Steps to reproduce the behavior

View https://purl.stanford.edu/bc934nk0577 (PDF) 

![1](https://user-images.githubusercontent.com/73732/82358414-56a7e800-99bb-11ea-9b78-e21ff481980b.gif)

View https://purl.stanford.edu/bb648mk7250 (3D)

![2](https://user-images.githubusercontent.com/73732/82358436-5dcef600-99bb-11ea-8601-be1a03004ee4.gif)

### Browser / Environment

MacOS 10.14.6 / Chrome 81/Edge 81
MacOS 10.14.6 / Firefox 76.0.1
MacOS 10.14.6 / Safari 13.1

**Comment by jkeck** [comment] 2020-05-19 21:50
This appears to have been caused by the chunking introduced in #1132.  Looking at ways to keep chunking, but may need to revert that work.  @mejackreed any thoughts on why, after chunking, it appears that jquery in certain modules can't access the DOM anymore?

**Comment by mejackreed** [comment] 2020-05-19 21:59
Nothing off the top of my head but happy to help dive into this.

**Comment by jkeck** [comment] 2020-05-19 21:59
I have a possible solution using `$(document).ready()` around the pack loaded modules.

**Comment by mejackreed** [comment] 2020-05-19 23:27
Resolved by @jkeck in #1155 👏

**Closed by mejackreed** 2020-05-19 23:27 UTC
Labels: bug
